package lista;

public class ListaDePalavras {
	private String cidades[] = {"HONG KONG","BANGKOK","LONDRES","SINGAPURA","MACAO","PARIS","DUBAI","NOVA YORK",
								"KUALA LUMPUR","SHENZHEN","ISTAMBUL","DÉLI","TÓQUIO","ROMA","MUMBAI","PRAGA",
								"MIAMI","AMSTERDÃ","SEUL","SHANGHAI","LOS ANGELES","LAS VEGAS","OSAKA","MILÃO",
								"VIENA","CANCUN","BERLIM","JOANESBURGO","VENEZA","MADRI","ORLANDO","DUBLIN",
								"FLORENÇA","MOSCOU","ATENAS","CAIRO","TORONTO","PEQUIM","SYDNEY","MUNIQUE",
								"BUDAPESTE","SÃO PETERSBURGO","JAKARTA","LISBOA","JERUSALÉM","KYOTO","BRUXELAS",
								"VANCOUVER","COPENHAGUE","SÃO FRANCISCO","VARSÓVIA","CRACÓVIA","MELBOURNE",
								"HONOLULU","MARRAQUEXE","CALCUTÁ","FRANKFURT","ESTOCOLMO","CIDADE DO MÉXICO",
								"BUENOS AIRES","LIMA","NICE","SANTIAGO","RIO DE JANEIRO","ABU DHABI","PORTO",
								"DOHA","IROSHIMA","NAGASAKI","YOKOHAMA","GENEBRA"};
	private String paises[] = {"CHINA","ÍNDIA","ESTADOS UNIDOS","INDONÉSIA","PAQUISTÃO","BRASIL","NIGÉRIA",
								"BANGLADESH","RÚSSIA","MÉXICO","JAPÃO","FILIPINAS","EGITO","ETIÓPIA","VIETNAM",
								"CONGO","TURQUIA","ALEMANHA","FRANÇA","TAILÂNDIA","REINO UNIDO","ITÁLIA",
								"ÁFRICA DO SUL","TANZÂNIA","MIANMAR","COREIA DO SUL","COLOMBIA","QUÊNIA",
								"ESPANHA","ARGENTINA","ARGÉLIA","UCRANIA","UGANDA","IRAQUE","POLÕNIA","CANADÁ",
								"MARROCOS","MALÁSIA","AFEGANISTÃO","VENEZUELA","PERU","ANGOLA","MOÇAMBIQUE",
								"NEPAL","CAMARÕES","MADAGASCAR","COSTA DO MARFIM","AUSTRÁLIA","IRLANDA",
								"SRI LANKA","BURKINA FASSO","ROMÊNIA","CHILE","ZÂMBIA","SÍRIA","EQUADOR","HOLANDA",
								"GUATEMALA","SENAGAL","SOMÁLIA","CAMBOJA","TUNISIA","HAITI","BOLÍVIA","BÉLGICA",
								"CUBA","GRÉCIA","JORDÂNIA","REPÚBLICA DOMINICANA","SUÉCIA","PORTUGAL","HUNGRIA",
								"HONDURAS","AUSTRIA","SUÍÇA","PARAGUAI","SÉVIA","BULGÁRIA","LÍBANO","NICARÁGUA",
								"DINAMARCA","FINLÂNDIA","ESLOVÁQUIA","NORUEGA","COSTA RICA","NOVA ZELÂNDIA",
								"PANAMÁ","CROÁCIA","GEÓRGIA","URUGUAI","ARMÊNIA","ALBÂNIA","LITUÂNIA","CATAR",
								"JAMAICA","ESLOVÊNIA","BAHREIN","ANDORRA"};
	private String animais[] = {"ABELHA","ABUTRE","ÁGUIA","ALBATROZ","ANCHOVA","ANDORINHA","ANTÍLOPE","ARANHA","ALCE","AVESTRUZ",
								"BABUÍNO","BACALHAU","BEIJA-FLOR","BESOURO","BICHO-DA-SEDA","BICHO-PREGUIÇA","BISONTE",
								"BORBOLETA","CACHALOTE","CACHORRO","CÁGADO","CALANGO","CAMALEÃO","CAMELO","CAMUNDONGO","CANÁRIO",
								"CANGURU","CAPIVARA","CARANGUEJO","CARNEIRO","CARRAPATO","CEGONHA","CENTOPEIA","CHINCHHILA",
								"CASCAVEL","CASTOR","CAVALO","CHIMPANZÉ","CIGARRA","CISNE","COALA","COELHO","COIOTE","CONDOR",
								"CORVO","CORUJA","DIABO-DA-TASMÂNIA","DONINHA","DROMEDÁRIO","ESCARAVELHO","ESCORPIÃO","ESPONJA",
								"CROCODILO","DRAGÃO DE COMODO","ELEFANTE","ESQUILO","GAFANHOTO","GALINHA","GAMBÁ","GIRAFA","GOLFINHO",
								"FLAMINGO","FORMIGA","FURÃO","GAZELA","GORILA","GRALHA","GROU","GUAXINIM","HAMSTER","HIPOPÓTAMO",
								"HARPIA","HOMEM","IGUANA","ÍBIS","INHAMBU","JABUTI","JACARÉ","JAGUATIRICA","JOÃO-DE-BARRO","JOANINHA",
								"LAGARTIXA","LAMPREIA","LEÃO-MARINHO","MACACO","MARIMBONDO","MEDUSA","MEXILHÃO","MORCEGO","MUSARANHO",
								"LAMBARI","LEOPARDO","LIBÉLULA","LINCE","MARRECO","ORANGOTANGO","ORNITORRINCO","OURIÇO-DO-MAR","PANDA",
								"PANTERA","PELICANO","PERCEVEJO","PERERECA","PERIQUITO","PERNILONGO","PAPAGAIO","PAVÃO","PEIXE-ESPADA",
								"PERU","PINGUIM","PIRANHA","QUERO-QUERO","RAPOSA","RINOCERONTE","SABIÁ","SALAMANDRA","SANGUESSUGA",
								"SARDINHA","SURICATE","TAMANDUÁ","TARTARUGA","TARÂNTULA","TIGRE","TOUPEIRA","TUCANO","VAGA-LUME",
								"TUCUNARÉ","URUBU","VEADO","VÍBORA","YORKSHIRE","ZEBRA"};
	private String filmes[] = {"UM SONHO DE LIBERDADE","O CAVALEIRO DAS TREVAS","A LISTA DE SCHINDLER","O SENHOR DOS ANÉIS",
								"STAR WARS","MATRIX","OS SETE SAMURAIS","CIDADE DE DEUS","O SILÊNCIO DOS INOCENTES","A VIDA É BELA",
								"OS SUSPEITOS","O RESGATE DO SOLDADO RYAN","A VIAGEM DE CHIHIRO","À ESPERA DE UM MILAGRE",
								"CASABLANCA","INTOCÁVEIS","OS TEMPOS MODERNOS","INDIANA JONES","O EXTERMINADOR DO FUTURO",
								"DE VOLTA PARA O FUTURO","GLADIADOR","O REI LEÃO","APOCALYPTO","O GRANDE DITADOR","CREPÚSCULO DOS DEUSES",
								"WALL-E","ALIENS","VALENTE","LARANJA MECÂNICA","CANTANDO NA CHUVA","TOY STORY","GOLPE DE MESTRE",
								"GÊNIO INDOMÁVEL","BATMAN BEGINS","DURO DE MATAR","DIVERTIDA MENTE","E O VENTO LEVOU","AURORA",
								"O SEXTO SENTIDO","PROCURANDO NEMO","ERA UMA VEZ EM TÓQUIO","ATÉ O ÚLTIMO HOMEM","COMO TREINAR O SEU DRAGÃO",
								"GAROTA EXEMPLAR","ILHA DO MEDO","LOGAN","THOR","BEN-HUR","JURASSIC PARK","HARRY POTTER","ROCKY",
								"MONSTROS SA","O ULTIMATO BOURNE","O MÁGICO DE OZ","ZOOTOPIA","A BELA E A FERA","SOCIEDADE DOS POETAS MORTOS",
								"PIRATAS DO CARIBE","HOMEM ARANHA","DOUTOR ESTRANHO","OS VINGADORES","LIGA DA JUSTIÇA","GUARDIÕES DA GALÁXIA",
								"OS OUTROS","JOGOS VORAZES","HOMEM FORMIGA","MULHER MARAVILHA","HOMEN DE FERRO","CAPITÃO AMÉRICA",
								"HOMENS DE PRETO","EU SOU A LENDA","O LIVRO DE ELI","A CABANA","KUNG FU PANDA"};
	
	public String getCidade(int random) {
		return cidades[random];
	}

	public String getPaises(int random) {
		return paises[random];
	}

	public String getAnimal(int random) {
		return animais[random];
	}

	public String getFilme(int random) {
		return filmes[random];
	}
	
	public String[] getTamVetCidades() {
		return cidades;
	}

	public String[] getTamVetPaises() {
		return paises;
	}

	public String[] getTamVetAnimais() {
		return animais;
	}

	public String[] getTamVetFilmes() {
		return filmes;
	}

}
